### ISSUE TITLE
Sometimes the sender of a transaction constructed by MPC signature was not the deriveAddress

### ISSUE THREAD

**Issue by jiguantong** [ringecosystem/xapi-contracts#11]
deriveAddress: 0xe8923abc48a7f0afa3c93c21bdfa4adcb35aefff
sendTxAddress: 0x3A5E15083C8932ABDe64a3bE14861924b024AEEb 
```
info:    2024-10-22T05:27:28Z | [  publisher   ] ==> [Sepolia-11155111] double check 70021766616531051842153016788507494922593962344450640499185811458, status: 0
info:    2024-10-22T05:27:28Z | [  publisher   ] ==> [70021766616531051842153016788507494922593962344450640499185811458] triggerPublish
info:    2024-10-22T05:27:28Z | [triggerPublish] ===> deriveAddress: 0xe8923abc48a7f0afa3c93c21bdfa4adcb35aefff
info:    2024-10-22T05:27:29Z | [triggerPublish] ===> gasLimit: 145334
info:    2024-10-22T05:27:29Z | [triggerPublish] ===> nonce: 7
info:    2024-10-22T05:27:30Z | [triggerPublish] ===> balance: 0.603273087565017414
info:    2024-10-22T05:27:31Z | [triggerPublish] ===> maxFeePerGas: 10572521131, maxPriorityFeePerGas: 1973674
info:    2024-10-22T05:27:31Z | [triggerPublish] ===> mpcConfig: {"mpc_contract":"v1.signer-prod.testnet","attached_balance":"999999999999999983222784"}
Receipts: CsjZbYpGNX81Mqgi1EAJT48bfbr3pdavwaZDL9tDYXmJ, 6V88QjhVNxPAaaATXC7Tovau86BerhpfvwYMXPuNDgYJ, 36WMFGgbaskvEfqXxuCgXHtGVTpiMF3PuWMAmsveHqsm
        Log [ormpaggregator.guantong.testnet]: before request signature, prepaidGas: 300000000000000, leftGas: 277153122437855
Receipts: ELSs6N64QVqKBSjWkhbNGK3q2ihtGhDnbqhfzuG6DMK7, BDZ48474yZsqJAJWJYuBEwvHCFZ4Td8npwCSQ2G8t5yR
        Log [ormpaggregator.guantong.testnet]: sign: predecessor=ormpaggregator.guantong.testnet, payload=Scalar(Uint(0x60661955C3D8DBE3E0540E10F7B24AF2FF2DF11579E7B0319EB9C3D6AA817D94)), path="XAPI-11155111", key_version=0
        Log [ormpaggregator.guantong.testnet]: [66,45,140,121,62,193,32,101,85,39,232,91,35,156,240,50,121,173,188,226,175,121,173,6,21,113,101,19,181,30,166,50]
Receipts: HC79f82dEZkwa686ygSoozK2a5rpx5pYvu8ByV2gj86, 9KxYqy53EqXV3nEEd8vAEiYv83ZcJiU5teYEkT1HpKri
        Log [ormpaggregator.guantong.testnet]: refund more than required deposit 0.800 NEAR to ormpaggregator.guantong.testnet
Receipt: 3Nkys4mr8PiHVe6e2Uq9FbHx7rrzqoL5Lk462RA5PtQr
        Log [ormpaggregator.guantong.testnet]: Signature is ready.
Receipt: A3Q4p3WmuJkTSDWVZFFSucgtj6qPKxDRH8b6tZNvT413
        Log [ormpaggregator.guantong.testnet]: publish_callback 70021766616531051842153016788507494922593962344450640499185811458, true, {"big_r":{"affine_point":"02760167562CDBB4BE83CD0AB516824FDCD650D03923489224B277E357F9664A66"},"s":{"scalar":"78F18E3F53D6D8C42D43DB87756A2AADDFF393B80C548B7C5CC1ED1466658C32"},"recovery_id":1}
        Log [ormpaggregator.guantong.testnet]: EVENT_JSON: {"standard":"nep297","version":"1.0.0","event":"Publish","data":{"request_id":"70021766616531051842153016788507494922593962344450640499185811458","response":{"request_id":"70021766616531051842153016788507494922593962344450640499185811458","started_at":"1728897292103951237","status":"PUBLISHED","valid_reporters":["guantong.testnet"],"reporter_reward_addresses":["0x9F33a4809aA708d7a399fedBa514e0A0d15EfA85"],"result":"test-result","chain_id":"11155111","updated_at":"1728897295187805215"},"call_data":"0xf58acf370000000000aa36a70000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000009f33a4809aa708d7a399fedba514e0a0d15efa85000000000000000000000000000000000000000000000000000000000000000b746573742d726573756c74000000000000000000000000000000000000000000","chain_config":{"chain_id":"11155111","xapi_address":"0x7535409663129A387e3e95fE18b940eaE04C2F25","reporters_fee":"300","publish_fee":"400","reward_address":"0x9F33a4809aA708d7a399fedBa514e0A0d15EfA85","version":"1729565126086929730"},"signature":"{\"big_r\":{\"affine_point\":\"02760167562CDBB4BE83CD0AB516824FDCD650D03923489224B277E357F9664A66\"},\"s\":{\"scalar\":\"78F18E3F53D6D8C42D43DB87756A2AADDFF393B80C548B7C5CC1ED1466658C32\"},\"recovery_id\":1}","mpc_options":{"nonce":"7","gas_limit":"145334","max_fee_per_gas":"10572521131","max_priority_fee_per_gas":"1973674"}}}
publish_external result {
  request_id: '70021766616531051842153016788507494922593962344450640499185811458',
  response: {
    request_id: '70021766616531051842153016788507494922593962344450640499185811458',
    started_at: '1728897292103951237',
    status: 'PUBLISHED',
    valid_reporters: [ 'guantong.testnet' ],
    reporter_reward_addresses: [ '0x9F33a4809aA708d7a399fedBa514e0A0d15EfA85' ],
    result: 'test-result',
    chain_id: '11155111',
    updated_at: '1728897295187805215'
  },
  call_data: '0xf58acf370000000000aa36a70000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000009f33a4809aa708d7a399fedba514e0a0d15efa85000000000000000000000000000000000000000000000000000000000000000b746573742d726573756c74000000000000000000000000000000000000000000',
  chain_config: {
    chain_id: '11155111',
    xapi_address: '0x7535409663129A387e3e95fE18b940eaE04C2F25',
    reporters_fee: '300',
    publish_fee: '400',
    reward_address: '0x9F33a4809aA708d7a399fedBa514e0A0d15EfA85',
    version: '1729565126086929730'
  },
  signature: '{"big_r":{"affine_point":"02760167562CDBB4BE83CD0AB516824FDCD650D03923489224B277E357F9664A66"},"s":{"scalar":"78F18E3F53D6D8C42D43DB87756A2AADDFF393B80C548B7C5CC1ED1466658C32"},"recovery_id":1}',
  mpc_options: {
    nonce: '7',
    gas_limit: '145334',
    max_fee_per_gas: '10572521131',
    max_priority_fee_per_gas: '1973674'
  }
}
relay publish mpc error TransactionRevertInstructionError: Transaction has been reverted by the EVM
    at /root/xapi-git/xapi-offchain/node_modules/web3-eth/lib/commonjs/utils/get_transaction_error.js:48:21
    at Generator.next (<anonymous>)
    at /root/xapi-git/xapi-offchain/node_modules/web3-eth/lib/commonjs/utils/get_transaction_error.js:24:71
    at new Promise (<anonymous>)
    at __awaiter (/root/xapi-git/xapi-offchain/node_modules/web3-eth/lib/commonjs/utils/get_transaction_error.js:20:12)
    at getTransactionError (/root/xapi-git/xapi-offchain/node_modules/web3-eth/lib/commonjs/utils/get_transaction_error.js:33:12)
    at SendTxHelper.<anonymous> (/root/xapi-git/xapi-offchain/node_modules/web3-eth/lib/commonjs/utils/send_tx_helper.js:79:84)
    at Generator.next (<anonymous>)
    at fulfilled (/root/xapi-git/xapi-offchain/node_modules/web3-eth/lib/commonjs/utils/send_tx_helper.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: undefined,
  reason: 'err: insufficient funds for gas * price + value: address 0x3A5E15083C8932ABDe64a3bE14861924b024AEEb have 0 want 1536546786052754 (supplied gas 145334)',
  signature: undefined,
  receipt: undefined,
  data: undefined,
  code: 402
}
```

**Comment by jiguantong** [comment]
Try https://github.com/near-examples/chainsig-script
![image](https://github.com/user-attachments/assets/23d3bbad-4135-4ed4-b5ba-e7873768556f)

**Comment by jiguantong** [comment]
error recovery_id https://github.com/ringecosystem/xapi-offchain/blob/471bc032b55dc115208cca8c9be4d59fe9ff9166/packages/publisher-client/src/command/start.ts#L266
